"""empty message

Revision ID: 0dd530ac5c38
Revises: 7eee27e2db2e
Create Date: 2018-06-14 14:32:59.881618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd530ac5c38'
down_revision = '7eee27e2db2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenecode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('scenecode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenecode')
    # ### end Alembic commands ###
