"""empty message

Revision ID: 217b6d7cb91c
Revises: 612805046311
Create Date: 2018-11-29 10:36:48.440806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '217b6d7cb91c'
down_revision = '612805046311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'ues_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('ues_date', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
