"""empty message

Revision ID: 3af7612ae0d7
Revises: a622d9c5467e
Create Date: 2018-11-26 10:23:06.424349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3af7612ae0d7'
down_revision = 'a622d9c5467e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('ues_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_create_time'), 'todos', ['create_time'], unique=False)
    op.drop_index('ix_task_list_create_time', table_name='task_list')
    op.drop_table('task_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('filename', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('ues_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='task_list_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_task_list_create_time', 'task_list', ['create_time'], unique=False)
    op.drop_index(op.f('ix_todos_create_time'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
