"""empty message

Revision ID: 418f2bb174b2
Revises: 
Create Date: 2018-11-20 16:30:20.368967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418f2bb174b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adcode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('adcode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commonparameters',
    sa.Column('dt', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('cgi', sa.String(length=50), nullable=False),
    sa.Column('tac', sa.Integer(), nullable=True),
    sa.Column('chinesename', sa.String(length=200), nullable=True),
    sa.Column('covertype', sa.String(length=50), nullable=True),
    sa.Column('scenario', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('earfcn', sa.Integer(), nullable=True),
    sa.Column('nettype', sa.String(length=50), nullable=True),
    sa.Column('pci', sa.Integer(), nullable=True),
    sa.Column('iscore', sa.Boolean(), nullable=True),
    sa.Column('gpslat', sa.Float(), nullable=True),
    sa.Column('gpslng', sa.Float(), nullable=True),
    sa.Column('bdlat', sa.Float(), nullable=True),
    sa.Column('bdlng', sa.Float(), nullable=True),
    sa.Column('angle', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('totaltilt', sa.Float(), nullable=True),
    sa.Column('iscounty', sa.Boolean(), nullable=True),
    sa.Column('isauto', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cgi')
    )
    op.create_table('commonparameters_tagged',
    sa.Column('dt', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('cgi', sa.String(length=50), nullable=False),
    sa.Column('tac', sa.Integer(), nullable=True),
    sa.Column('chinesename', sa.String(length=200), nullable=True),
    sa.Column('covertype', sa.String(length=50), nullable=True),
    sa.Column('scenario', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('earfcn', sa.Integer(), nullable=True),
    sa.Column('nettype', sa.String(length=50), nullable=True),
    sa.Column('pci', sa.Integer(), nullable=True),
    sa.Column('iscore', sa.Boolean(), nullable=True),
    sa.Column('gpslat', sa.Float(), nullable=True),
    sa.Column('gpslng', sa.Float(), nullable=True),
    sa.Column('bdlat', sa.Float(), nullable=True),
    sa.Column('bdlng', sa.Float(), nullable=True),
    sa.Column('angle', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('totaltilt', sa.Float(), nullable=True),
    sa.Column('iscounty', sa.Boolean(), nullable=True),
    sa.Column('isauto', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('residential_flag', sa.String(length=50), nullable=True),
    sa.Column('hospital_flag', sa.String(length=50), nullable=True),
    sa.Column('beauty_spot_flag', sa.String(length=50), nullable=True),
    sa.Column('college_flag', sa.String(length=50), nullable=True),
    sa.Column('food_centre_flag', sa.String(length=50), nullable=True),
    sa.Column('subway_flag', sa.String(length=50), nullable=True),
    sa.Column('high_speed_flag', sa.String(length=50), nullable=True),
    sa.Column('high_speed_rail_flag', sa.String(length=50), nullable=True),
    sa.Column('viaduct_flag', sa.String(length=50), nullable=True),
    sa.Column('high_rise_flag', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cgi')
    )
    op.create_table('gaodemapscene',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('city_adcode', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('longtitude', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('typecode', sa.String(length=20), nullable=True),
    sa.Column('classify', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('shape', sa.Text(), nullable=True),
    sa.Column('wgs_long', sa.Float(), nullable=True),
    sa.Column('wgs_lat', sa.Float(), nullable=True),
    sa.Column('wgs_shape', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenecode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('scenecode', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('city_adcode', sa.String(length=6), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('type_code', sa.String(length=6), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('final_grid', sa.Integer(), nullable=True),
    sa.Column('adsl_server_url', sa.String(length=100), nullable=False),
    sa.Column('adsl_auth', sa.String(length=100), nullable=False),
    sa.Column('keys', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('city_adcode', 'type_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_create_time'), 'note', ['create_time'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_create_time'), 'comment', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_create_time'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_note_create_time'), table_name='note')
    op.drop_table('note')
    op.drop_table('user')
    op.drop_table('scrape_missions')
    op.drop_table('scenecode')
    op.drop_table('gaodemapscene')
    op.drop_table('commonparameters_tagged')
    op.drop_table('commonparameters')
    op.drop_table('adcode')
    # ### end Alembic commands ###
