"""empty message

Revision ID: 612805046311
Revises: ceb647dcd124
Create Date: 2018-11-29 10:23:13.221827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '612805046311'
down_revision = 'ceb647dcd124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aa')
    op.drop_table('text')
    op.drop_table('GaodeMapScene')
    op.add_column('todos', sa.Column('todo_city', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'todo_city')
    op.create_table('GaodeMapScene',
    sa.Column('id', mysql.CHAR(length=20), nullable=False),
    sa.Column('province', mysql.CHAR(length=50), nullable=True),
    sa.Column('city', mysql.CHAR(length=50), nullable=True),
    sa.Column('name', mysql.CHAR(length=50), nullable=True),
    sa.Column('city_adcode', mysql.CHAR(length=20), nullable=True),
    sa.Column('district', mysql.CHAR(length=50), nullable=True),
    sa.Column('address', mysql.CHAR(length=100), nullable=True),
    sa.Column('longtitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('lat', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('type', mysql.CHAR(length=100), nullable=True),
    sa.Column('typecode', mysql.CHAR(length=20), nullable=True),
    sa.Column('classify', mysql.CHAR(length=100), nullable=True),
    sa.Column('area', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('shape', mysql.TEXT(), nullable=True),
    sa.Column('wgs_long', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('wgs_lat', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('wgs_shape', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('text',
    sa.Column('dt', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('province', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('region', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('cgi', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False),
    sa.Column('tac', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('chinesename', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True),
    sa.Column('covertype', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('scenario', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('vendor', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('earfcn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nettype', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('pci', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('iscore', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('gpslat', mysql.FLOAT(), nullable=True),
    sa.Column('gpslng', mysql.FLOAT(), nullable=True),
    sa.Column('bdlat', mysql.FLOAT(), nullable=True),
    sa.Column('bdlng', mysql.FLOAT(), nullable=True),
    sa.Column('angle', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('height', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('totaltilt', mysql.FLOAT(), nullable=True),
    sa.Column('iscounty', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('isauto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('residential_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('hospital_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('beauty_spot_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('college_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('food_centre_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('subway_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('high_speed_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('high_speed_rail_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('viaduct_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('high_rise_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.PrimaryKeyConstraint('cgi'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('aa',
    sa.Column('dt', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('province', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('region', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('cgi', mysql.VARCHAR(charset='utf8', length=50), nullable=False),
    sa.Column('tac', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('chinesename', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True),
    sa.Column('covertype', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('scenario', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('vendor', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('earfcn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nettype', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('pci', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('iscore', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('gpslat', mysql.FLOAT(), nullable=True),
    sa.Column('gpslng', mysql.FLOAT(), nullable=True),
    sa.Column('bdlat', mysql.FLOAT(), nullable=True),
    sa.Column('bdlng', mysql.FLOAT(), nullable=True),
    sa.Column('angle', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('height', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('totaltilt', mysql.FLOAT(), nullable=True),
    sa.Column('iscounty', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('isauto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('residential_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('hospital_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('beauty_spot_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('college_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('food_centre_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('subway_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('high_speed_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('high_speed_rail_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('viaduct_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.Column('high_rise_flag', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True),
    sa.PrimaryKeyConstraint('cgi'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###
