"""empty message

Revision ID: 68f107be7d2d
Revises: 9278c68ecbc8
Create Date: 2018-11-23 10:45:13.954813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f107be7d2d'
down_revision = '9278c68ecbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_lisk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.Column('ues_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_lisk_create_time'), 'task_lisk', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_lisk_create_time'), table_name='task_lisk')
    op.drop_table('task_lisk')
    # ### end Alembic commands ###
