"""empty message

Revision ID: 8764fc01f2ee
Revises: 3af7612ae0d7
Create Date: 2018-11-26 10:38:31.149474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8764fc01f2ee'
down_revision = '3af7612ae0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('filename', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
