"""empty message

Revision ID: a0af907440af
Revises: 8764fc01f2ee
Create Date: 2018-11-26 10:45:36.205112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0af907440af'
down_revision = '8764fc01f2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
