"""empty message

Revision ID: a622d9c5467e
Revises: 576d06c90a18
Create Date: 2018-11-26 09:56:49.216273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a622d9c5467e'
down_revision = '576d06c90a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_list', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('task_list', 'activate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_list', sa.Column('activate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('task_list', 'status')
    # ### end Alembic commands ###
