"""empty message

Revision ID: ae955d6b624f
Revises: 0dd530ac5c38
Create Date: 2018-06-19 10:04:24.056218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae955d6b624f'
down_revision = '0dd530ac5c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('adcode', sa.Integer(), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('scenecode', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gaodemapscene_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaodemapscene_test',
    sa.Column('id', mysql.CHAR(length=20), nullable=False),
    sa.Column('province', mysql.CHAR(length=50), nullable=True),
    sa.Column('city', mysql.CHAR(length=50), nullable=True),
    sa.Column('name', mysql.CHAR(length=50), nullable=True),
    sa.Column('city_adcode', mysql.CHAR(length=20), nullable=False),
    sa.Column('district', mysql.CHAR(length=50), nullable=True),
    sa.Column('address', mysql.CHAR(length=100), nullable=True),
    sa.Column('longtitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('lat', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('type', mysql.CHAR(length=100), nullable=True),
    sa.Column('typecode', mysql.CHAR(length=20), nullable=True),
    sa.Column('classify', mysql.CHAR(length=100), nullable=True),
    sa.Column('area', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('shape', mysql.TEXT(), nullable=True),
    sa.Column('wgs_long', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('wgs_lat', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('wgs_shape', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'city_adcode'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('database')
    # ### end Alembic commands ###
