"""empty message

Revision ID: da2a54dfd277
Revises: 56333b67ee49
Create Date: 2018-06-19 14:26:01.879230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2a54dfd277'
down_revision = '56333b67ee49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataoperation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('adcode', sa.Integer(), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('scenecode', sa.Integer(), nullable=False),
    sa.Column('adsl_server_url', sa.String(length=50), nullable=False),
    sa.Column('adsl_server_auth', sa.String(length=50), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataoperation')
    # ### end Alembic commands ###
